backend:
  name: github
  repo: caiquecamargo/lp-creator
  branch: main
  auth_endpoint: oauth
  site_domain: ""
  base_url: https://lp.interone.com.br
locale: pt
logo_url: /logo.svg
site_url: https://lp.interone.com.br
display_url: https://lp.interone.com.br
media_folder: src/assets/images
public_folder: /assets/images
media_libraries:
  default:
    config:
      max_file_size: 25000000
      slugify_filename: true
      transformations:
        raster_image:
          format: webp
          quality: 85
          width: 2048
          height: 2048
collections: []
singletons:
  - name: page
    label: Configurações da Página
    icon: page_info
    file: src/data/page.json
    summary: "{{title}}"
    thumbnail: false
    editor:
      preview: false
    fields:
      - widget: hidden
        name: slug
        label: slug
        default: page-config
      - widget: hidden
        name: title
        label: Título
        default: Configurações da Página
      - widget: object
        name: header
        label: Header e topo
        fields:
          - widget: image
            name: logo
            label: Logo da Página
            required: true
          - widget: image
            name: marker
            label: Marcação
            required: true
          - widget: image
            name: banner
            label: Banner (1440x780)
            required: true
      - widget: list
        name: chars
        label: Características
        default: []
        required: false
        fields:
          - widget: string
            name: label
            label: Label da Característica
      - widget: object
        name: form
        label: Configurações do Formulário
        fields:
          - widget: image
            name: bannerForm
            label: Banner do Formulário (190x550)
            required: true
          - widget: string
            name: formTitle
            label: Título do Formulário
            required: true
          - widget: list
            name: formFields
            label: Campos do Formulário
            default: []
            required: false
            types:
              - widget: object
                name: text
                label: Campo de Texto
                fields:
                  - widget: string
                    name: name
                    label: Nome do campo
                  - widget: string
                    name: label
                    label: Label do Campo
                  - widget: boolean
                    name: required
                    label: Campo Obrigatório
                    default: false
              - widget: object
                name: select
                label: Campo de Seleção
                fields:
                  - widget: string
                    name: name
                    label: Nome do campo
                  - widget: string
                    name: label
                    label: Label do Campo
                  - widget: list
                    name: options
                    label: Opções de Seleção
                    default: []
                    required: false
                    fields:
                      - widget: string
                        name: label
                        label: Label da Opção
                      - widget: string
                        name: value
                        label: Valor da Opção
                  - widget: boolean
                    name: required
                    label: Campo Obrigatório
                    default: false
              - widget: object
                name: textarea
                label: Campo de Texto Longo
                fields:
                  - widget: string
                    name: name
                    label: Nome do campo
                  - widget: string
                    name: label
                    label: Label do Campo
                  - widget: boolean
                    name: required
                    label: Campo Obrigatório
                    default: false
          - widget: text
            name: formSuccessMessage
            label: Mensagem de Sucesso do Formulário
            required: true
          - widget: text
            name: button
            label: Label do Botão
            required: true
      - widget: object
        name: footer
        label: Configurações do Footer
        fields:
          - widget: image
            name: logo
            label: Logo do Footer
            required: true
          - widget: list
            name: phones
            label: Telefones
            default: []
            required: false
            fields:
              - widget: string
                name: label
                label: Label do Telefone
          - widget: list
            name: addresses
            label: Endereços
            default: []
            required: false
            fields:
              - widget: string
                name: label
                label: Label do Endereço
